sudo: false

language: php

php:
  - 7.2
  - 7.1

before_script:
    - composer self-update
    - composer --prefer-source --dev install
    - cp phpunit.xml.dist phpunit.xml

script: 
    - vendor/bin/phpunit -c phpunit.xml
